[package]
name = "pug"
version = "0.1.0"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "A web framework for rust."
homepage = "https://github.com/saturn-xiv/put"
license = "MIT"

[features]
default = ["postgresql", "mysql", "sqlite", "redis", "rabbitmq"]

postgresql = ["rocket_contrib/diesel_postgres_pool"]
mysql = ["rocket_contrib/diesel_mysql_pool"]
sqlite = ["rocket_contrib/diesel_sqlite_pool"]
redis = ["rocket_contrib/redis_pool"]
rabbitmq = []

[dependencies]
log = "0.4"
error-chain = "0.12"
chrono = "0.4"
chrono-tz = "0.5"
serde = "1"
serde_derive = "1"
jsonwebtoken = "5"
serde_json = "1"
rocket = "0.4.0-rc.1"

[dependencies.rocket_contrib]
version = "0.4.0-rc.1"
default-features = false
features = []
