[package]
name = "pug"
version = "0.1.0"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "A web framework for rust."
homepage = "https://github.com/saturn-xiv/put"
license = "MIT"

[features]
default = ["postgresql", "mysql", "sqlite", "redis", "rabbitmq", "sodium", "zeromq"]

postgresql = ["rocket_contrib/diesel_postgres_pool"]
mysql = ["rocket_contrib/diesel_mysql_pool"]
sqlite = ["rocket_contrib/diesel_sqlite_pool"]
redis = ["rocket_contrib/redis_pool"]
rabbitmq = []
zeromq = []
sodium = ["sodiumoxide"]

[dependencies]
log = "0.4"
log4rs = "0.8"
error-chain = "0.12"
chrono = "0.4"
chrono-tz = "0.5"
serde = "1"
serde_derive = "1"
jsonwebtoken = "5"
serde_json = "1"
clap = "2.32"
base64 = "0.10"
sha2 = "0.8"
sodiumoxide = {version="0.1.0", optional=true}
hyper = "0.12"
futures = "0.1" 
rocket = "0.4.0-rc.1"

[dependencies.rocket_contrib]
version = "0.4.0-rc.1"
default-features = false
features = []
